-- ============================================
-- CREATE HEAVEN_VIDEOS TABLE (with BIGINT id)
-- ============================================
-- Simplified version matching user's requested structure
-- ============================================

BEGIN;

-- Create table with bigint id (auto-incrementing)
CREATE TABLE IF NOT EXISTS public.heaven_videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT heaven_videos_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

COMMIT;

-- ============================================
-- VERIFICATION
-- ============================================

-- Check if table was created
SELECT 
  table_name,
  table_type
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_name = 'heaven_videos';

-- Check table structure
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
  AND table_name = 'heaven_videos'
ORDER BY ordinal_position;

